version: '3.8'

services:
  db:
    image: postgres:15
    container_name: db_telesecundaria
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=escuela_db
      - POSTGRES_USER=admin_escuela
      - POSTGRES_PASSWORD=secreto_local
    ports:
      - "5432:5432"

volumes:
  postgres_data: